name: Codacy Security Scan

on: [push, pull_request]

jobs:
  codacy-analysis:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Run ESLint Analysis
      run: docker run --rm -v $(pwd):/src codacy/codacy-eslint:5.9.1 /src

    - name: Run PMD Analysis
      run: docker run --rm -v $(pwd):/src codacy/codacy-pmd:3.10.2 /src

    - name: Run PMD Legacy Analysis
      run: docker run --rm -v $(pwd):/src codacy/codacy-pmdjava:2.0.0-pmdlegacy.57fdbf2 /src

    - name: Run Codacy CLI
      run: docker run --rm -v $(pwd):/src codacy/codacy-analysis-cli:latest analyze --verbose --project-token ${{ secrets.CODACY_PROJECT_TOKEN }}
